export const ACTION_TYPES = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  UPDATE_USER: "UPDATE_USER",
  RESET_USER_STATE: "RESET_USER_STATE",
  SHOW_TOAST_MESSAGE: "SHOW_TOAST_MESSAGE",
};
